name = "indie"
license = "MIT"
licenselink = "https://github.com/onurakpolat/hugo-indie-theme/blob/master/LICENSE"
description = "The most beautiful theme for Hugo"
homepage = "https://github.com/onurakpolat/hugo-indie-theme"
tags = ["design",
        "blog",
        "portfolio",
        "responsive",
        "amp",
        "personal",
        "startup",
        "blog"
        ]
features = ["projects",
            "flexboxgrid",
            "responsive",
            "analytics",
            "blog",
            "teaching",
            "contact"
            ]
min_version = 0.19

[author]
  name = "Onur Akpolat"
  homepage = "https://indie.academy/"